/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Gustavo Primolan
 */
public class TelaDescricao extends javax.swing.JFrame {

    /**
     * Creates new form TelaDescricao
     */
    public TelaDescricao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADWE");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html><b>Grupo de emoções sobre destinos de outros:</b><br/> 1) feliz por outro, satisfação com eventos desejáveis para outro;  <br/>2) ressentimento, insatisfação com eventos desejáveis para outro;  <br/>3) regozijo, satisfação com eventos indesejáveis para outro;  <br/>4) compaixão, insatisfação com eventos indesejáveis para outro.  <br/><br/><b>Grupo de emoções de bem-estar:</b>  <br/>1) alegria, satisfação com eventos desejáveis para si mesmo;  <br/>2) sofrimento, insatisfação com eventos indesejáveis para si mesmo.  <br/><br/><b>Grupo de emoções de atribuição:</b>  <br/>1) orgulho, aprovação de uma ação atribuída a si mesmo;  <br/>2) vergonha, desaprovação de uma ação atribuída a si mesmo;  <br/>3) admiração, aprovação de uma ação atribuída a outro agente;  <br/>4) reprovação, desaprovação de uma ação atribuída a outro agente.  <br/><br/><b>Grupo de emoções de atração:</b> <br/>1) amor, gostar de um objeto;  <br/>2) ódio, não gostar de um objeto;  <br/><br/><b>Grupo de emoções baseadas em expectativas:</b> <br/>1) esperança, satisfação com a expectativa de um evento futuro;  <br/>1.1) júbilo, satisfação com uma esperança confirmada;  <br/>1.2) desapontamento, insatisfação com uma esperança não confirmada;  <br/>2) medo, insatisfação com a expectativa de um evento futuro;  <br/>2.1) medo confirmado, insatisfação com um medo confirmado;  <br/>2.2) alívio, satisfação com um medo não confirmado.  <br/><br/><b>Grupo de emoções compostas de bem-estar e atribuição:</b> <br/>1) gratificação: união das condições de ocorrência de alegria e orgulho; <br/>2) remorso: união das condições de ocorrência de sofrimento e vergonha; <br/>3) gratidão: união das condições de ocorrência de alegria e admiração; <br/>4) raiva: união das condições de ocorrência de sofrimento e reprovação</html> ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDescricao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
